using IronPdf;
using Newtonsoft.Json.Linq;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var app = builder.Build();

app.UseSwagger();
app.UseSwaggerUI();


// ================================
// LOAD SETTINGS FROM appsettings
// ================================

var configuration = builder.Configuration;

string ironPdfLicense =
    configuration["IronPdf:LicenseKey"] ?? "";

string webhook =
    configuration["Bitrix24:Webhook"] ?? "";


// ================================
// APPLY LICENSE
// ================================

IronPdf.License.LicenseKey = ironPdfLicense;


// ================================
// HOME ENDPOINT
// ================================

app.MapGet("/", () =>
{
    return Results.Ok("Bitrix24 IronPDF API Running");
});


// ================================
// GENERATE PDF ENDPOINT
// ================================

app.MapGet("/generate-proposal/{dealId}", async (int dealId) =>
{
    try
    {
        using var http = new HttpClient();

        var response = await http.GetAsync(
            $"{webhook}crm.deal.get.json?id={dealId}");

        var content =
            await response.Content.ReadAsStringAsync();

        if (!response.IsSuccessStatusCode)
        {
            return Results.Text(
                $"Bitrix24 API Error:\n\n{content}");
        }

        var json = JObject.Parse(content);

        var deal = json["result"];

        if (deal == null)
        {
            return Results.Text("Deal not found");
        }

        string title =
            deal["TITLE"]?.ToString()
            ?? "Untitled Deal";

        string amount =
            deal["OPPORTUNITY"]?.ToString()
            ?? "0";

        string comments =
            deal["COMMENTS"]?.ToString()
            ?? "No comments available";

        string stage =
            deal["STAGE_ID"]?.ToString()
            ?? "N/A";

        string created =
            deal["DATE_CREATE"]?.ToString()
            ?? "N/A";

        string currency =
            deal["CURRENCY_ID"]?.ToString()
            ?? "INR";


        // ================================
        // HTML TEMPLATE
        // ================================

        var html = $@"

<!DOCTYPE html>

<html>

<head>

<meta charset='utf-8'>

<style>

body {{
    font-family: Arial;
    margin: 0;
    padding: 0;
    background: #f4f4f4;
    color: #333;
}}

.header {{
    background: #0f172a;
    color: white;
    padding: 40px;
}}

.header h1 {{
    margin: 0;
    font-size: 40px;
}}

.header p {{
    margin-top: 10px;
    opacity: 0.9;
}}

.container {{
    padding: 40px;
}}

.card {{
    background: white;
    border-radius: 12px;
    padding: 25px;
    margin-bottom: 25px;
    box-shadow: 0 2px 10px rgba(0,0,0,0.08);
}}

.amount {{
    font-size: 40px;
    font-weight: bold;
    color: #16a34a;
    margin-top: 10px;
}}

table {{
    width: 100%;
    border-collapse: collapse;
}}

td {{
    padding: 14px;
    border-bottom: 1px solid #ddd;
}}

.footer {{
    margin-top: 50px;
    font-size: 12px;
    color: #666;
    text-align: center;
}}

.notes {{
    line-height: 1.7;
}}

</style>

</head>

<body>

<div class='header'>

    <h1>Business Proposal</h1>

    <p>
        Generated from Bitrix24 CRM using IronPDF
    </p>

</div>

<div class='container'>

    <div class='card'>

        <h2>{title}</h2>

        <p>Total Deal Value</p>

        <div class='amount'>
            {currency} {amount}
        </div>

    </div>

    <div class='card'>

        <h3>Deal Information</h3>

        <table>

            <tr>
                <td><strong>Deal ID</strong></td>
                <td>{dealId}</td>
            </tr>

            <tr>
                <td><strong>Stage</strong></td>
                <td>{stage}</td>
            </tr>

            <tr>
                <td><strong>Created Date</strong></td>
                <td>{created}</td>
            </tr>

        </table>

    </div>

    <div class='card'>

        <h3>Comments / Notes</h3>

        <div class='notes'>
            {comments}
        </div>

    </div>

    <div class='card'>

        <h3>Services Included</h3>

        <ul>
            <li>CRM Consultation</li>
            <li>Automation Setup</li>
            <li>Workflow Optimization</li>
            <li>Technical Support</li>
            <li>Implementation Guidance</li>
        </ul>

    </div>

    <div class='footer'>

        Generated by Rohit Tripathi<br/>
        Bitrix24 + IronPDF Integration Demo

    </div>

</div>

</body>

</html>

";


        // ================================
        // PDF GENERATION
        // ================================

        Directory.CreateDirectory("GeneratedPDFs");

        var renderer = new ChromePdfRenderer();

        var pdf =
            renderer.RenderHtmlAsPdf(html);

        var fileName =
            $"GeneratedPDFs/Proposal_{dealId}.pdf";

        pdf.SaveAs(fileName);

        Console.WriteLine(
            $"PDF SAVED AT: {Path.GetFullPath(fileName)}");

        return Results.File(
            File.ReadAllBytes(fileName),
            "application/pdf",
            $"Proposal_{dealId}.pdf");
    }
    catch (Exception ex)
    {
        return Results.Text(
            $"FULL ERROR:\n\n{ex}");
    }
});

app.Run();